// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trfmpmwkkzdemcbutbuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZm1wbXdra3pkZW1jYnV0YnVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxMzIzOTYsImV4cCI6MjA5MDcwODM5Nn0.7V4-BMyVW8cwbRDZaxD4YN5ZjOIO9WerckR9sJezibs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});